"""Streamlit web UI. Run locally with: uv run streamlit run app.py

Two modes:
- Sample reports: browse pre-generated reports. Costs nothing, so it is safe for a public demo.
- Live research: runs the agent. Uses ANTHROPIC_API_KEY from the environment / Streamlit secrets,
  or a key the visitor pastes in (kept only in their browser session).
"""

from __future__ import annotations

import os
import sys
import re
from pathlib import Path

import anthropic
import streamlit as st
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent / "src"))  # so it runs without installing the package (Streamlit Cloud)

load_dotenv()
load_dotenv(Path.home() / ".config" / "equity-research-agent" / ".env")  # key saved outside the repo

from equity_agent import ResearchError, Settings, research  # noqa: E402

SAMPLES = Path(__file__).parent / "sample_reports"

st.set_page_config(page_title="AI Equity Research Agent", page_icon="📈", layout="wide")
st.title("📈 AI Equity Research Agent")
st.caption(
    "An AI agent that downloads a company's SEC filings, researches it the way an analyst would - "
    "10 years of financials, filings search, DCF, peers, insider activity and news - and writes an investment memo. "
    "Built with Claude, SEC EDGAR and Yahoo Finance. Educational project, not investment advice."
)


def server_key() -> str | None:
    try:
        return st.secrets.get("ANTHROPIC_API_KEY")
    except Exception:  # no secrets.toml
        return os.getenv("ANTHROPIC_API_KEY")


with st.sidebar:
    mode = st.radio("Mode", ["Sample reports", "Live research"])
    st.divider()
    st.markdown(
        "**How it works**\n"
        "1. Claude plans the research and calls tools\n"
        "2. Tools fetch filings (SEC EDGAR), financials and prices (Yahoo Finance) and news (web search)\n"
        "3. Claude writes a structured report with a valuation and bull/bear cases"
    )
    if os.getenv("REPO_URL"):
        st.markdown(f"[Source code]({os.getenv('REPO_URL')})")

if mode == "Sample reports":
    reports = sorted(p for p in SAMPLES.glob("*.md") if not p.name.endswith(".tools.md"))
    if not reports:
        st.info("No sample reports yet. Generate one with `uv run equity-research NVDA --out sample_reports`.")
        st.stop()
    choice = st.selectbox("Report", reports, format_func=lambda p: p.stem.replace("_", " - "))
    text = choice.read_text()
    meta = re.search(r"<!-- generated by .*?model: (\S+) \| cost: \$(\S+) .*?tool calls: (\d+)", text)
    if meta:
        c1, c2, c3 = st.columns(3)
        model = meta.group(1).replace("claude-", "Claude ").replace("-", " ").replace(" 5 5", " 5.5").title()
        c1.metric("Model", model)
        c2.metric("Cost to generate", f"${meta.group(2)}")
        c3.metric("Tool calls", meta.group(3))
    html_file = choice.with_suffix(".html")
    if html_file.exists():
        st.iframe(html_file.read_text(), height=1400)
        pdf_file = choice.with_suffix(".pdf")
        if pdf_file.exists():
            st.download_button("Download PDF", pdf_file.read_bytes(), file_name=pdf_file.name)
    else:
        st.markdown(text)
    st.stop()

# ---- Live research ----------------------------------------------------------
key = server_key()
if not key:
    key = st.sidebar.text_input("Anthropic API key", type="password",
                                help="Used only for this session; never stored.")

col1, col2, col3 = st.columns([2, 1, 1])
ticker = col1.text_input("Ticker", placeholder="e.g. NVDA").strip().upper()
effort = col2.selectbox("Depth", ["low", "medium", "high"], index=1)
max_cost = col3.number_input("Spending cap (USD)", 0.10, 3.00, 1.50, 0.10)

if st.button("Write investment memo", type="primary", disabled=not (ticker and key)):
    settings = Settings(effort=effort, max_cost_usd=max_cost)
    cost_box = st.empty()
    with st.status(f"Researching {ticker}...", expanded=True) as status:
        def on_event(kind: str, p: dict) -> None:
            if kind == "tool_call":
                args = ", ".join(f"{k}={v}" for k, v in p["input"].items() if k != "url")
                st.write(f"🔧 `{p['name']}`  {args}")
            elif kind == "download":
                st.write(f"📄 downloaded `{p['doc_id']}`")
            elif kind == "web_search":
                st.write(f"🔎 searching the web: *{p['query']}*")
            elif kind == "status":
                status.update(label=f"{ticker}: {p['message']}")
            elif kind == "cost":
                cost_box.caption(f"Running cost: ${p['cost_usd']:.3f}")

        try:
            result = research(ticker, settings, on_event, client=anthropic.Anthropic(api_key=key))
        except ResearchError as exc:
            status.update(label="Failed", state="error")
            st.error(str(exc))
            st.stop()
        status.update(label=f"{ticker}: done - {len(result.tool_calls)} tool calls, "
                            f"${result.cost_usd:.3f}", state="complete", expanded=False)

    from equity_agent.render import render_html
    html = render_html(result.report, ticker, result.tool_calls,
                       f"Model: {result.model} | cost ${result.cost_usd:.2f} | {len(result.tool_calls)} tool calls.")
    st.download_button("Download memo (.html)", html, file_name=f"{ticker}_memo.html")
    st.iframe(html, height=1400)
