"""Command line entry point: `equity-research NVDA`."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

from dotenv import load_dotenv


def save_report(result, out_dir: Path) -> Path:
    """Write the memo as Markdown, a styled HTML report with charts, and a PDF when a browser is available."""
    from datetime import datetime

    from .render import html_to_pdf, previous_recommendations, render_html

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{result.ticker}_memo_{date.today():%Y-%m-%d}.md"
    u = result.usage
    footer = (
        f"\n\n<!-- generated by equity-research-agent | model: {result.model} | "
        f"cost: ${result.cost_usd:.3f} | input: {u.input_tokens} | cache read: {u.cache_read_tokens} | "
        f"cache write: {u.cache_write_tokens} | output: {u.output_tokens} | web searches: {u.web_searches} | "
        f"tool calls: {len(result.tool_calls)} -->\n"
    )
    path.write_text(result.report + footer)
    (path.with_suffix(".tools.json")).write_text(json.dumps(result.tool_calls, indent=1, default=str))

    meta = f"Model: {result.model} | cost ${result.cost_usd:.2f} | {len(result.tool_calls)} tool calls."
    html_path = path.with_suffix(".html")
    previous = previous_recommendations(result.ticker, out_dir, exclude=path)
    html_path.write_text(render_html(result.report, result.ticker, result.tool_calls, meta,
                                     generated_at=datetime.now(), previous=previous))
    html_to_pdf(html_path)
    return path


def main(argv: list[str] | None = None) -> int:
    load_dotenv()
    load_dotenv(Path.home() / ".config" / "equity-research-agent" / ".env")  # key saved outside the repo
    from .agent import ResearchError, Settings, research  # after .env is loaded

    parser = argparse.ArgumentParser(description="Download a company's SEC filings and write an AI investment memo.")
    parser.add_argument("ticker", help="Stock ticker, e.g. NVDA")
    parser.add_argument("--model", help="Claude model ID (default: claude-sonnet-5-5)")
    parser.add_argument("--effort", choices=["low", "medium", "high"], help="Reasoning effort (default: medium)")
    parser.add_argument("--max-cost", type=float, help="Spending cap in USD for this memo (default: 1.50)")
    parser.add_argument("--deep", action="store_true",
                        help="Highest quality: Claude Opus 5.5, high effort, $3 cap (about 2-3x the cost)")
    parser.add_argument("--spanish", action="store_true",
                        help="Also write a Spanish version of the memo (about $0.10 extra)")
    parser.add_argument("--no-fact-check", action="store_true", help="Skip the fact-check pass")
    parser.add_argument("--out", type=Path, default=Path("reports"), help="Output folder (default: reports/)")
    args = parser.parse_args(argv)

    settings = Settings()
    if args.deep:
        settings.model, settings.effort, settings.max_cost_usd = "claude-opus-5-5", "high", 3.00
    if args.no_fact_check:
        settings.fact_check = False
    if args.model:
        settings.model = args.model
    if args.effort:
        settings.effort = args.effort
    if args.max_cost is not None:
        settings.max_cost_usd = args.max_cost

    def on_event(kind: str, p: dict) -> None:
        if kind == "tool_call":
            shown = ", ".join(f"{k}={v}" for k, v in p["input"].items() if k != "url")
            print(f"  -> {p['name']}({shown})", file=sys.stderr)
        elif kind == "web_search":
            print(f"  -> web_search: {p['query']}", file=sys.stderr)
        elif kind == "download":
            print(f"  downloaded {p['doc_id']}", file=sys.stderr)
        elif kind == "status":
            print(p["message"], file=sys.stderr)
        elif kind == "cost":
            print(f"     running cost: ${p['cost_usd']:.3f}", file=sys.stderr)

    print(f"Researching {args.ticker.upper()} with {settings.model} "
          f"(effort={settings.effort}, cap=${settings.max_cost_usd:.2f})", file=sys.stderr)
    try:
        result = research(args.ticker, settings, on_event)
    except ResearchError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    path = save_report(result, args.out)
    if args.spanish:
        from .translate import translate_file
        try:
            translate_file(path, log=lambda m: print(m, file=sys.stderr))
        except Exception as exc:
            print(f"Spanish translation failed: {exc}", file=sys.stderr)
    print(f"\nDone. Memo saved to {path.with_suffix('.html')} (+ .md/.pdf)  |  cost ${result.cost_usd:.3f}  |  "
          f"{len(result.tool_calls)} tool calls", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
